export const ADD_TODO = 'ADD_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const CHANGE_TODO_COMPLETION_STATUS = 'CHANGE_TODO_COMPLETION_STATUS';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';